language: node_js
sudo: false
dist: trusty
node_js:
  - "8"
cache: npm

compiler: clang-4.0
env:
  - CXX=clang-4.0

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-4.0

install:
  - npm ci

before_script:
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - bash /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"

  - git clone https://github.com/tree-sitter/tree-sitter.git /tmp/tree-sitter
  - pushd /tmp/tree-sitter
  - git checkout 4db132ff94a5775f0c06b743ff1c603251222d4f
  - git submodule update --init --recursive
  - cargo install --path cli
  - popd

  - mkdir -p corpus/

script:
  - npm install
  - npm run generate
  - npm run test

