language: node_js
sudo: false
dist: trusty
node_js:
  - "8"
cache: npm

compiler: clang-4.0
env:
  - CXX=clang-4.0

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-4.0

install:
  - npm ci

before_script:
  - mkdir -p corpus/

script:
  - npm run generate
  - npm run test

