language: node_js
sudo: false
dist: trusty
node_js:
  - "8"
cache: npm

compiler: clang-4.0
env:
  - CXX=clang-4.0
  - PATH="$HOME/.cargo/bin:$PATH"

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-4.0
      - rustc
      - cargo

install:
  - npm ci

before_script:
  - mkdir -p corpus/
  - pushd ./vendor/tree-sitter && cargo install --path cli && popd

script:
  - npm run generate
  - npm run test

